In [ ]:
import pandas as pd
matriculas=pd.read_excel('https://robertohincapie.com/data/libro_merge.xlsx', sheet_name='matriculas')
usuarios=pd.read_excel('https://robertohincapie.com/data/libro_merge.xlsx', sheet_name='usuarios')
cursos=pd.read_excel('https://robertohincapie.com/data/libro_merge.xlsx', sheet_name='cursos')

print('Cursos:\n', cursos)
print('\nUsuarios:\n', usuarios)
print('\nMatriculas:\n',matriculas)

Cursos:
   Curso (*)                   Nombres  IDProfesor
0     MAT01       CÁLCULO DIFERENCIAL        1234
1     MAT02          CÁLCULO INTEGRAL        1234
2     FIS01  ECUACIONES DIFERENCIALES        1234
3     FIS02         CÁLCULO VECTORIAL        4321

Usuarios:
    ID (*)         Nombres            Apellidos
0    1234   ROBIN OCTAVIO      ZULUAGA GALLEGO
1    4321  MARIA LUZ AIDA       SABOGAL TAMAYO
2    5432         ANTONIO    ESCAMILLA PINILLA
3    1001   JORGE ENRIQUE  SALDARRIAGA ESCOBAR
4    1002    EMIGDIO JOSE      MENDOZA FANDIÑO
5    1003   SILVIO ANDRES     SALAZAR MARTINEZ
6    1004     JUAN MIGUEL    VASQUEZ CIFUENTES

Matriculas:
    Curso (*)  IDEstudiante (*)
0      MAT01              5432
1      MAT01              1001
2      MAT01              1002
3      MAT01              5432
4      MAT02              1003
5      MAT02              1004
6      FIS01              5432
7      FIS01              1001
8      FIS01              1002
9      FIS01              1003
10     FIS01              1004
11     FIS02              1001
12     FIS02              1002
13     FIS02              1003
14     FIS02              1004

In [ ]:
#Agreguemos el nombre de los usuarios al dataframe actual y creemos otro dataframe
resumen=matriculas.merge(right=usuarios, how='left', left_on='IDEstudiante (*)', right_on='ID (*)')
resumen

   Curso (*)  IDEstudiante (*)  ID (*)        Nombres            Apellidos
0      MAT01              5432    5432        ANTONIO    ESCAMILLA PINILLA
1      MAT01              1001    1001  JORGE ENRIQUE  SALDARRIAGA ESCOBAR
2      MAT01              1002    1002   EMIGDIO JOSE      MENDOZA FANDIÑO
3      MAT01              5432    5432        ANTONIO    ESCAMILLA PINILLA
4      MAT02              1003    1003  SILVIO ANDRES     SALAZAR MARTINEZ
5      MAT02              1004    1004    JUAN MIGUEL    VASQUEZ CIFUENTES
6      FIS01              5432    5432        ANTONIO    ESCAMILLA PINILLA
7      FIS01              1001    1001  JORGE ENRIQUE  SALDARRIAGA ESCOBAR
8      FIS01              1002    1002   EMIGDIO JOSE      MENDOZA FANDIÑO
9      FIS01              1003    1003  SILVIO ANDRES     SALAZAR MARTINEZ
10     FIS01              1004    1004    JUAN MIGUEL    VASQUEZ CIFUENTES
11     FIS02              1001    1001  JORGE ENRIQUE  SALDARRIAGA ESCOBAR
12     FIS02              1002    1002   EMIGDIO JOSE      MENDOZA FANDIÑO
13     FIS02              1003    1003  SILVIO ANDRES     SALAZAR MARTINEZ
14     FIS02              1004    1004    JUAN MIGUEL    VASQUEZ CIFUENTES

In [ ]:
#Reorganicemos un poco el resultado, cambiando el nombre de las columnas que encontramos y
#eliminando el campo de ID que queda sobrando
resumen=resumen.rename(columns={'Nombres':'Nombres estudiante','Apellidos':'Apellidos estudiante'})
resumen=resumen.drop('ID (*)', axis=1)
resumen.head()

  Curso (*)  IDEstudiante (*) Nombres estudiante Apellidos estudiante
0     MAT01              5432            ANTONIO    ESCAMILLA PINILLA
1     MAT01              1001      JORGE ENRIQUE  SALDARRIAGA ESCOBAR
2     MAT01              1002       EMIGDIO JOSE      MENDOZA FANDIÑO
3     MAT01              5432            ANTONIO    ESCAMILLA PINILLA
4     MAT02              1003      SILVIO ANDRES     SALAZAR MARTINEZ

In [ ]:
#Ahora traigamos el nombre del profesor y el curso al dataframe
resumen=resumen.merge(right=cursos, how='left', left_on='Curso (*)', right_on='Curso (*)')
resumen=resumen.rename(columns={'Nombres':'Nombre curso'})
resumen.head()

,Curso (*),IDEstudiante (*),Nombres estudiante,Apellidos estudiante,Nombre curso,IDProfesor
0,MAT01,5432,ANTONIO,ESCAMILLA PINILLA,CÁLCULO DIFERENCIAL,1234
1,MAT01,1001,JORGE ENRIQUE,SALDARRIAGA ESCOBAR,CÁLCULO DIFERENCIAL,1234
2,MAT01,1002,EMIGDIO JOSE,MENDOZA FANDIÑO,CÁLCULO DIFERENCIAL,1234
3,MAT01,5432,ANTONIO,ESCAMILLA PINILLA,CÁLCULO DIFERENCIAL,1234
4,MAT02,1003,SILVIO ANDRES,SALAZAR MARTINEZ,CÁLCULO INTEGRAL,1234

In [ ]:
#Finalmente agreguemos el nombre del profesor a DF actual
resumen=resumen.merge(right=usuarios, how='left', left_on='IDProfesor', right_on='ID (*)')
resumen=resumen.rename(columns={'Nombres':'Nombres Profesor','Apellidos':'Apellidos Profesor'})
resumen=resumen.drop('ID (*)', axis=1)
resumen

,Curso (*),IDEstudiante (*),Nombres estudiante,Apellidos estudiante,Nombre curso,IDProfesor,Nombres Profesor,Apellidos Profesor
0,MAT01,5432,ANTONIO,ESCAMILLA PINILLA,CÁLCULO DIFERENCIAL,1234,ROBIN OCTAVIO,ZULUAGA GALLEGO
1,MAT01,1001,JORGE ENRIQUE,SALDARRIAGA ESCOBAR,CÁLCULO DIFERENCIAL,1234,ROBIN OCTAVIO,ZULUAGA GALLEGO
2,MAT01,1002,EMIGDIO JOSE,MENDOZA FANDIÑO,CÁLCULO DIFERENCIAL,1234,ROBIN OCTAVIO,ZULUAGA GALLEGO
3,MAT01,5432,ANTONIO,ESCAMILLA PINILLA,CÁLCULO DIFERENCIAL,1234,ROBIN OCTAVIO,ZULUAGA GALLEGO
4,MAT02,1003,SILVIO ANDRES,SALAZAR MARTINEZ,CÁLCULO INTEGRAL,1234,ROBIN OCTAVIO,ZULUAGA GALLEGO
5,MAT02,1004,JUAN MIGUEL,VASQUEZ CIFUENTES,CÁLCULO INTEGRAL,1234,ROBIN OCTAVIO,ZULUAGA GALLEGO
6,FIS01,5432,ANTONIO,ESCAMILLA PINILLA,ECUACIONES DIFERENCIALES,1234,ROBIN OCTAVIO,ZULUAGA GALLEGO
7,FIS01,1001,JORGE ENRIQUE,SALDARRIAGA ESCOBAR,ECUACIONES DIFERENCIALES,1234,ROBIN OCTAVIO,ZULUAGA GALLEGO
8,FIS01,1002,EMIGDIO JOSE,MENDOZA FANDIÑO,ECUACIONES DIFERENCIALES,1234,ROBIN OCTAVIO,ZULUAGA GALLEGO
9,FIS01,1003,SILVIO ANDRES,SALAZAR MARTINEZ,ECUACIONES DIFERENCIALES,1234,ROBIN OCTAVIO,ZULUAGA GALLEGO
10,FIS01,1004,JUAN MIGUEL,VASQUEZ CIFUENTES,ECUACIONES DIFERENCIALES,1234,ROBIN OCTAVIO,ZULUAGA GALLEGO
11,FIS02,1001,JORGE ENRIQUE,SALDARRIAGA ESCOBAR,CÁLCULO VECTORIAL,4321,MARIA LUZ AIDA,SABOGAL TAMAYO
12,FIS02,1002,EMIGDIO JOSE,MENDOZA FANDIÑO,CÁLCULO VECTORIAL,4321,MARIA LUZ AIDA,SABOGAL TAMAYO
13,FIS02,1003,SILVIO ANDRES,SALAZAR MARTINEZ,CÁLCULO VECTORIAL,4321,MARIA LUZ AIDA,SABOGAL TAMAYO
14,FIS02,1004,JUAN MIGUEL,VASQUEZ CIFUENTES,CÁLCULO VECTORIAL,4321,MARIA LUZ AIDA,SABOGAL TAMAYO